server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/db02
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
